Calculator on two patterns
ZalyalovIldar/PatternsProject pull request #1
Opened 2019-02-16 15:08 UTC by alxarsnk

Калькулятор на MVP и VIPER

2019-02-16 15:10 UTC, alxarsnk commented
Воу, а что с конфликтом делать?)

2019-02-16 15:37 UTC, ZalyalovIldar requested changes
В общем ок, но есть что подправить в стилистике кода: 
1) Все протоколы покрыть комментариями в MVP/VIPER 
2) Вынести все константы(!!!) 
3) Так же можешь вынести бизнес логику из интерактора/презентера(в MVP) в отдельный менеджер по подсчету, сейчас у тебя копипаст кода и там и там по сути, а мог бы переиспользовать) 

**Bug:** любое число -> процент -> любое число  
**Ожидаемый результат:** 
Новое число вводится на чисто 
**Фактический результат:** 
Новое число добавляется в процент от числа

2019-02-16 15:37 UTC, ZalyalovIldar commented on PatternsHomeWork/PatternsHomeWork/Extensions.swift
> +
сверху только 1 отступ оставляем)

2019-02-16 15:37 UTC, ZalyalovIldar commented on PatternsHomeWork/PatternsHomeWork/Extensions.swift
> +    func isWhole () -> Bool {
комментарий

2019-02-16 15:37 UTC, ZalyalovIldar commented on PatternsHomeWork/PatternsHomeWork/Extensions.swift
> +    {
фигурная скобка на той же строке где метод, чтоб было однотипно, а то два метода, и у обоих разный стиль)

2019-02-16 15:37 UTC, ZalyalovIldar commented on PatternsHomeWork/PatternsHomeWork/Extensions.swift
> +    {
ну и коммент тоже

2019-02-16 15:37 UTC, ZalyalovIldar commented on PatternsHomeWork/PatternsHomeWork/UIActionManager.swift
> +//  UIActionManager.swift
Нейминг не очень понятный) Лучше что то вроде AlertsManager

2019-02-16 15:37 UTC, ZalyalovIldar commented on PatternsHomeWork/PatternsHomeWork/UIActionManager.swift
> +}
сверху один отступ, а снизу 0 - стандартная стилистика)

2019-02-16 15:37 UTC, ZalyalovIldar commented on PatternsHomeWork/PatternsHomeWork/UIActionManager.swift
> +protocol UIActionManagerProtocol: AnyObject {
комментарии

2019-02-16 15:37 UTC, ZalyalovIldar commented on PatternsHomeWork/PatternsHomeWork/UIActionManager.swift
> +        let indicator = UIActivityIndicatorView()
не очень понял зачем это, думаю можно обойтись)

2019-02-16 15:37 UTC, ZalyalovIldar commented on PatternsHomeWork/PatternsHomeWork/UIActionManager.swift
> +    func showAlert(_ text: String) -> UIAlertController {
если Title алерта "Error", то в сигнатуре метода ты тоже должен как то сказать об этом) 
тип showErrorAlert()

2019-02-16 15:37 UTC, ZalyalovIldar commented on PatternsHomeWork/PatternsHomeWork/VIPER/Interactor/VIPERInteractor.swift
> +    func printOne() {
во всех методах куча констант, все выносить и пере использовать

2019-02-16 15:37 UTC, ZalyalovIldar commented on PatternsHomeWork/PatternsHomeWork/VIPER/Interactor/VIPERInteractor.swift
> +            switch lastOperation {
все операции лучше вынести в enum

2019-02-16 15:37 UTC, ZalyalovIldar commented on PatternsHomeWork/PatternsHomeWork/VIPER/Interactor/VIPERInteractorInput.swift
> +    func printOne()
ухх сколько методов конечно)) Ну давай для всех комментарии)

2019-02-16 15:37 UTC, ZalyalovIldar commented on PatternsHomeWork/PatternsHomeWork/VIPER/Interactor/VIPERInteractorInput.swift
> +    func printOne()
Названии методов не корректные по отношению к Interactor-у, ты как бы говоришь ему "распечатай единицу", это больше похоже на метод View. Попробуй поиграться с неймингом.

2019-02-16 15:37 UTC, ZalyalovIldar commented on PatternsHomeWork/PatternsHomeWork/VIPER/Interactor/VIPERInteractorOutput.swift
> +    func didFinishedMainDisplay(_ name: String?)
комментарии

2019-02-16 15:37 UTC, ZalyalovIldar commented on PatternsHomeWork/PatternsHomeWork/VIPER/Presenter/VIPERPresenter.swift
> +        router.showAlert(name!)
если передаешь опционал, то веди его до конца, тем более Алерт принимает опционал)

2019-02-16 15:37 UTC, ZalyalovIldar commented on PatternsHomeWork/PatternsHomeWork/VIPER/Router/VIPERRouter.swift
> +        let alert = UIAlertController(title: "Error", message: text, preferredStyle: .alert)
У тебя же есть менеджер Алертов, давай туда теперь все это, и его сюды ижектируй)

2019-02-20 14:20 UTC, ZalyalovIldar approved these changes
Баг не пофиксился все же(

2019-02-20 14:20 UTC, closed without merging