Turbo calculator
ZalyalovIldar/PatternsProject pull request #3
Opened 2019-02-17 18:36 UTC by novpeter

2019-02-20 15:04 UTC, ZalyalovIldar requested changes
Нормас, лайауты тк вообще красава, но чутка подправить нужно)

2019-02-20 15:04 UTC, ZalyalovIldar commented on Calculator/MVP/View/MVPCalculatorController.swift
> +        resultLabel.text = result ?? "Nan";
константа)

2019-02-20 15:04 UTC, ZalyalovIldar commented on Calculator/MVP/View/MVPCalculatorController.swift
> +        let alert = UIAlertController(title: "Hey, bro!", message: message, preferredStyle: .alert)
Лучше вынеси алерт в алерт менеджер или в фабрику алертов)

2019-02-20 15:04 UTC, ZalyalovIldar commented on Calculator/MVP/Presenter/MVPPresenter.swift
> +    func didOperationButtonPressed(_ tag: Int!) {
в этом методе куча констант)

2019-02-20 15:04 UTC, ZalyalovIldar commented on Calculator/MVP/Presenter/MVPPresenter.swift
> +    /// Tag of math operation
отступ перед строкой

2019-02-20 15:04 UTC, ZalyalovIldar commented on Calculator/MVP/Presenter/MVPPresenter.swift
> +    func didOperationButtonPressed(_ tag: Int!) {
+ логику подсчет стоит вынести в отдельный менеджер Калькулятора и переиспользовать его в вайпер модуле, а то тут такое полотно)

2019-02-20 15:04 UTC, ZalyalovIldar commented on Calculator/MVP/View/MVPCalculatorController.swift
> +        }
если тебе не нужен блок экшена кнопки, то не стоит раскрывать его, просто поставь nil туды)

2019-02-20 15:04 UTC, ZalyalovIldar commented on Calculator/MVP/View/MVPViewOutput.swift
> +    func didOperationButtonPressed(_ tag: Int!)
в протоколах форс не указывается) Чикни во всех местах плиз)

2019-02-20 15:04 UTC, ZalyalovIldar commented on Calculator/VIPER/Interactor/VIPERInteractor.swift
> +    /// Tag of math operation
отступ сверху)

2019-02-20 15:04 UTC, ZalyalovIldar commented on Calculator/VIPER/Router/VIPERRouter.swift
> +        UIAlertView.self
здрасте, эт еще чо?)

2019-02-20 16:26 UTC, novpeter commented on Calculator/VIPER/Router/VIPERRouter.swift
> +        UIAlertView.self
Да с пары взял))

2019-02-20 18:32 UTC, novpeter commented on Calculator/MVP/View/MVPCalculatorController.swift
> +        let alert = UIAlertController(title: "Hey, bro!", message: message, preferredStyle: .alert)
Я думаю ради одного метода нет смысла выносить

2019-02-23 11:25 UTC, ZalyalovIldar approved these changes

2019-02-23 11:26 UTC, ZalyalovIldar commented
🥇

2019-02-23 11:26 UTC, closed without merging